### ISSUE TITLE
Help for the UI (and others stuff)

### ISSUE THREAD

**Issue by azlux** [azlux/Simple-URL-Shortener#1]
Answer to this issue if you want to help me for this project.

Please add the preferred topic (At the moment, I mostly need UI help) :
- the UI (CSS, I want to avoid JS as much as possible)
- The code (PHP, not that clean)
- The DB (mariadb or sqlite3) - If you think I've miss something.

**Comment by Spokeek** [comment]
Maybe PostgreSql for the database (maybe).

For my part, i think i may help for **CSS**

**Comment by mkody** [comment]
Multiple DB options is a plus, especially if the SQL requests are standard. :P 
sqlite3 is a good option for a self-hosted private shortener, and you don't need something as huge as pgsql.
