### ISSUE TITLE
missing .htaccess?

### ISSUE THREAD

**Issue by JC-os** [azlux/Simple-URL-Shortener#2]
Hello,
I've installed the software but it does not seems to work properly:
https://go.josephcosta.org/yUtA8

Also after login I have a white page.

You refer to an .htaccess file wich I can not find in the repository, could you please add it or give instructions in the README.md > Apache configuration (.htaccess) :?

Best regards
Joseph

**Comment by azlux** [comment]
Hi,
The .htaccess have been deleted by mistake while the code rewrite last month.

It's was : 
```
<IfModule mod_rewrite.c>
    RewriteEngine on

    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d

    RewriteRule ^(.*)$ ./index.php?site=$1
</IfModule>

<Files "database.sqlite3">
    Order Allow,Deny
    Deny from all
</Files>
```

But it not optimized, the htaccess was checking if the URL is a file, if not, use the rewrite rule.
If you know htaccess, you can rewrite the config to allow `/assets` and `/favicon.ico` and rewrite all other requests how isn't a `.php` file.

PR are accepted (I don't use apache for now)

**Comment by JC-os** [comment]
Hi,
And thank you for your quick answer, unfortunately I don’t know htaccess to contribute to optimize the directives.
With your directives, the redirect from short url to long url works fine.

The signin process is still not working.
I can see mysql table users is not creating any record after sign in.
I’ve tried to deactivate mod security but it still does not insert records.

I am currently using php 7.1, this might cause an issue?

Thank you,
Joseph

**Comment by azlux** [comment]
Have you change the config ` define('ALLOW_SIGNIN', 'false'); ` to True ?
If it's the case, you can check the url ask by the browser (F12, then network tab) and check if you don't have any error into apache logs.

**Comment by JC-os** [comment]
Yes I did.

In network tab I see two POST with orange triangle status code:
https://go.josephcosta.org/login.php?signin <https://go.josephcosta.org/login.php?signin>

HTTP/2.0 307 Temporary Redirect
server: nginx
date: Tue, 30 Jul 2019 22:06:34 GMT
content-type: text/html
content-length: 164
location: https://go.josephcosta.org/login.php?signin&cprotect=1
set-cookie: o2switch-PowerBoost-Protect=5427a59d9fd3c3930f8a332156c1c9cf; path=/
X-Firefox-Spdy: h2

https://go.josephcosta.org/login.php?signin&cprotect=1 <https://go.josephcosta.org/login.php?signin&cprotect=1>

HTTP/2.0 302 Found
server: nginx
date: Tue, 30 Jul 2019 22:06:34 GMT
content-type: text/html; charset=UTF-8
content-length: 0
location: https://go.josephcosta.org
x-powered-by: PHP/7.1.30
expires: Thu, 19 Nov 1981 08:52:00 GMT
cache-control: no-store, no-cache, must-revalidate
pragma: no-cache
X-Firefox-Spdy: h2

I don’t see errors in the apache logs.

Excuse me but here in Italy it is midnight and have to shutdown for now.
I’ll be back tomorrow morning to debug this together.

Thank you.

**Comment by azlux** [comment]
Should be good now. Please update.

**Comment by JC-os** [comment]
Yes it is good now.

May be it would be useful for apache users to add the .htaccess file in the repository or in the  in the README.md > Apache configuration (.htaccess).

Thank you very much, KISS is a good approach for unexpert users like me :)
