### ISSUE TITLE
User-submitted data isn't being sanitized, leading to stored XSS

### ISSUE THREAD

**Issue by 0x0banana** [azlux/Simple-URL-Shortener#3]
Hi, 

Loving this shortnener and it's really helped with some projects I'm working on for work. When setting this up in my env, I noted that the application isn't escaping html special characters nor stripping tags within the `shorten.php` file. This lead to me being able carry our a stored XSS on my own shortener. 

**Test case:**
By adding the following to a new url to shorten, arbitrary JavaScript will be executed when viewing created links: `https://google.com"><script>alert(0)</script>`

**Affected Code (lines 112-114):**

```
$url = $_POST['url'];
$comment = (!empty($_POST['comment'])) ? $_POST['comment'] : NULL;
$custom = (!empty($_POST['custom'])) ? $_POST['custom'] : NULL;
```
---

I appended htmlspecialchars and strip_tags to the variables being accepted, which let to arbitrary JavaScript no longer executing. I'm sure there is probably a better way to do this, however, it is a quick fix. 

**Fixed Code:**

```
$url = htmlspecialchars(strip_tags($_POST['url']));
$comment = (!empty($_POST['comment'])) ? htmlspecialchars(strip_tags($_POST['comment'])) : NULL;
$custom = (!empty($_POST['custom'])) ? htmlspecialchars(strip_tags($_POST['custom'])) : NULL;
```

I am happy to fork and submit a PR if that's easier. 

Thanks,
0x0Banana

**Comment by azlux** [comment]
Hi. Thank for the issue. It's really usefull

I'm not actually at home. I can merge a PR but not pushing code for thz next week.
