### ISSUE TITLE
URL_SIZE

### ISSUE THREAD

**Issue by mostlygucci** [azlux/Simple-URL-Shortener#5]
In the config.php file you can‘t change the URL_SIZE. I changed 5 characters to an other number but then the shortener doesn‘t work. There is a white page at shorten.php

**Comment by azlux** [comment]
Do you have any apache/nginx error log ?

**Comment by mostlygucci** [comment]
Where can I check this?

**Comment by azlux** [comment]
into `/var/log/ngnix/error.log` or `/var/log/apache/error.log`

**Comment by mostlygucci** [comment]
Fatal error: Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'short' at row 1 in /storage/ssd2/185/12987185/public_html/shorten.php:46 Stack trace: #0 /storage/ssd2/185/12987185/public_html/shorten.php(46): PDOStatement->execute(Array) #1 /storage/ssd2/185/12987185/public_html/shorten.php(115): short(Object(PDO), 'UNKNOWN', 'https://google....', 'Gljddkj', NULL) #2 {main} thrown in /storage/ssd2/185/12987185/public_html/shorten.php on line 46

**Comment by azlux** [comment]
Ho. I've forgot to change the database. The issue appears because the database use 5 letter entries. I will change that tomorrow.

**Comment by mostlygucci** [comment]
Okay Great
Thank you

**Comment by azlux** [comment]
Hi, what if I add a limit like : URL_SIZE can be change between 2 and 10 ?

**Comment by mostlygucci** [comment]
15 would be be better I think. Because some people want to Write words or sentences as custom url.

**Comment by mostlygucci** [comment]
Did you already change it?

**Comment by mostlygucci** [comment]
Sorry I am new to github. What did you just do?

**Comment by azlux** [comment]
I've push the changes. You can retry to install the database.

**Comment by mostlygucci** [comment]
Okay thanks i try it

**Comment by mostlygucci** [comment]
SQLSTATE[HY000] [1045] ProxySQL Error: Access denied for user 'id12987185_fcksme'@'2a02:4780:bad:f00d::e' (using password: YES)
Notice: Constant DATABASE_TYPE already defined in /storage/ssd2/185/12987185/public_html/inc/config.php on line 2

Notice: Constant MYSQL_HOST already defined in /storage/ssd2/185/12987185/public_html/inc/config.php on line 5

Notice: Constant MYSQL_DATABASE already defined in /storage/ssd2/185/12987185/public_html/inc/config.php on line 6

Notice: Constant MYSQL_USER already defined in /storage/ssd2/185/12987185/public_html/inc/config.php on line 7

Notice: Constant MYSQL_PASSWORD already defined in /storage/ssd2/185/12987185/public_html/inc/config.php on line 8

Notice: Constant SQLITE3_FILE already defined in /storage/ssd2/185/12987185/public_html/inc/config.php on line 11

Notice: Constant DEFAULT_URL already defined in /storage/ssd2/185/12987185/public_html/inc/config.php on line 13

Notice: Constant URL_SIZE already defined in /storage/ssd2/185/12987185/public_html/inc/config.php on line 14

Notice: Constant WEB_THEME already defined in /storage/ssd2/185/12987185/public_html/inc/config.php on line 15

Notice: Constant PUBLIC_INSTANCE already defined in /storage/ssd2/185/12987185/public_html/inc/config.php on line 16

Notice: Constant ALLOW_SIGNIN already defined in /storage/ssd2/185/12987185/public_html/inc/config.php on line 17

Notice: Undefined variable: connexion in /storage/ssd2/185/12987185/public_html/installation.php on line 9

Fatal error: Uncaught Error: Call to a member function errorCode() on null in /storage/ssd2/185/12987185/public_html/installation.php:9 Stack trace: #0 {main} thrown in /storage/ssd2/185/12987185/public_html/installation.php on line 9

**Comment by mostlygucci** [comment]
Never mind. I got it. I had to delete the installation.php file :/

**Comment by azlux** [comment]
Great !

**Comment by mostlygucci** [comment]
Thank you very much!
