### ISSUE TITLE
SQLite Error when registering

### ISSUE THREAD

**Issue by cyni0s** [azlux/Simple-URL-Shortener#6]
I´m running an Apache Webserver on PHP version 7.2 and when trying to register the admin user it just gives the following exception:

`Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1 no such table: users in /www/htdocs/login.php:17 Stack trace: #0 /www/htdocs/login.php(17): PDO->query('SELECT count(*)...') #1 {main} thrown in /www/htdocs/login.php on line 17`

The installation was done multiple times following your installation instructions. 
Thank you for your help.

**Comment by azlux** [comment]
What is you DATABASE_TYPE value in the config file ?
The database is created at the install. Can you connect to it  and make a `show tables;` or `.tables`(if sqlite?).

**Comment by cyni0s** [comment]
my config values are:
`define('DATABASE_TYPE', 'sqlite3'); //mysql or sqlite3`
`define('SQLITE3_FILE', './database.sqlite3');`

There is only one table in the sqlite database: shortener

**Comment by azlux** [comment]
Here the table you should have.
https://github.com/azlux/Simple-URL-Shortener/blob/master/installation.php#L11-L28
If the first table is created, I don't understand why the second is not. Can you check is there are entry missing on the table ?

**Comment by cyni0s** [comment]
No the Shortener table is created proberly
```
CREATE TABLE `shortener` (
      `short` char(5) NOT NULL,
      `url` varchar(700) NOT NULL,
      `comment` char(30) DEFAULT NULL,
      `views` int(11) DEFAULT NULL,
      `username` varchar(25) DEFAULT NULL,
      `date` datetime NOT NULL,
      PRIMARY KEY (`short`)
      );
```

So just to try it out I modified the installation.php and deleted the first table creation. Now the user registration works just fine with only the warning that headers were already been created.

Edit: modified installlation.php as .txt because I cannot upload .php files here
[modified_installation.txt](https://github.com/azlux/Simple-URL-Shortener/files/4638463/modified_installation.txt)

**Comment by azlux** [comment]
good. That is a weird issue you face here.

**Comment by cyni0s** [comment]
I'm happy with that fix and if I'm the only person confrontated with this I would close the issue now. Thanks for your quick help and time :)
