### ISSUE TITLE
Use relative URLs instead of absolute

### ISSUE THREAD

**Issue by bubeck** [azlux/Simple-URL-Shortener#8]
Throughout the HTML code you use absolute URLs, e.g.

https://github.com/azlux/Simple-URL-Shortener/blob/d35d4e57111128b3156431af3d948f1a13e4ff59/list.php#L81

This breaks using SUS in a subdirectory, like "https://xyz.com/go/". So I propose to change this to relative URLs, like

`<img src="assets/img/delete-icon.png"/> `

**Comment by gandalf458** [comment]
Seconded
